Repository aukletio/Auklet-Agent-C, pull requests merged in 2018-11, with the labels that each got.

#1 Migrate from ESG-USA to aukletio
  .circleci/config.yml
  .devops/calculate-app-version.sh
  .devops/calculateChangelogs.js
  .devops/deploy.sh
  .devops/determineVersionChange.js
  .devops/post-release.sh
  .devops/ssh-config-aukletio
  .devops/test_and_coverage.sh
  .devops/updateProdReleasePr.sh
  .devops/validate-pr.sh
  .devops/validatePr.js
  .esg
Labels: devops

#3 Release Candidate Review
  .circleci/config.yml
  .devops/calculate-app-version.sh
  .devops/calculateChangelogs.js
  .devops/deploy.sh
  .devops/determineVersionChange.js
  .devops/post-release.sh
  .devops/ssh-config-aukletio
  .devops/test_and_coverage.sh
  .devops/updateProdReleasePr.sh
  .devops/validate-pr.sh
  .devops/validatePr.js
  .esg
Labels: release

#4 Update instructions for bug reports
  README.md
  docs/CONTRIBUTING.md
Labels: devops

#5 Fixing Code Climate Links
  README.md
Labels: bug

#6 Release Candidate Review
  README.md
  docs/CONTRIBUTING.md
Labels: release

#7 Release Review
  .circleci/config.yml
  .devops/calculate-app-version.sh
  .devops/calculateChangelogs.js
  .devops/deploy.sh
  .devops/determineVersionChange.js
  .devops/post-release.sh
  .devops/ssh-config-aukletio
  .devops/test_and_coverage.sh
  .devops/updateProdReleasePr.sh
  .devops/validate-pr.sh
  .devops/validatePr.js
  .esg
  README.md
  docs/CONTRIBUTING.md
Labels: release

#8 APM-1692: Build agent for ARM 6/7/8
  .devops/deploy.sh
  arch-grid.csv
Labels: enhancement
